

ref:
  genome: "mouse"
  genome_index: "/shares/CIBIO-Storage/CIBIO/sharedLC/mouse_genome/mouse_ref_gene_index_star.2.7.9"




#10X
scRNAseqType: "CB_UMI_Simple"
whitelist: "resources/whitelist_10X_v2_737K-august-2016.txt"


organism: mm10
